import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"

    >


      <body className="layout">

        <header className=" site-header">
          <div className="container site-header-inner">
            <nav className="site-nav">
              <a href="/">Home</a>
              <a href="/courses">Courses</a>
              <a href="/instructors">Instructors</a>
            </nav>
          </div>

        </header>
        <main className="layout-main">

          {children}

        </main>

        <footer className="site-footer">
          <div className="container">
            <p className="site-footer-copy">
              Copy& right
            </p>
          </div>

        </footer>

      </body>


    </html>
  );
}
