import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"

    >

    


      <body className="layout">

        <header className=" site-header">
          <div className="container site-header-inner">
            <form action="/search" method="get" className="header-search">

              <input type="search" placeholder="nextJs/react" name="q" className="input header-search-input" />
              <button className="btn btn-primary btn-sm">Search</button>
            </form>
            <nav className="site-nav">
              <a href="/" className="site-nav-link">Home</a>
              <a href="/courses" className="site-nav-link">Courses</a>
              <a href="/instructors" className="site-nav-link">Instructors</a>
            </nav>
          </div>

        </header>
        <main className="layout-main">

          {children}

        </main>

        <footer className="site-footer">
          <div className="container">
            <p className="site-footer-copy">
              Copy& right
            </p>
          </div>

        </footer>

      </body>


    </html>
  );
}
